/** Chaves centralizadas do React Query — permanecem as mesmas quando os serviços usarem a API real. */
export const qk = {
  councilors: ["councilors"] as const,
  councilor: (id: string) => ["councilors", id] as const,
  councilorTimeline: (id: string) => ["councilors", id, "timeline"] as const,
  councilorTasks: (id: string) => ["councilors", id, "tasks"] as const,
  councilorRegistrations: (id: string) => ["councilors", id, "registrations"] as const,
  councilorCertificates: (id: string) => ["councilors", id, "certificates"] as const,
  councilorCommunications: (id: string) => ["councilors", id, "communications"] as const,
  chambers: ["chambers"] as const,
  chamber: (id: string) => ["chambers", id] as const,
  chamberCouncilors: (id: string) => ["chambers", id, "councilors"] as const,
  chamberEvents: (id: string) => ["chambers", id, "events"] as const,
  chamberActivity: (id: string) => ["chambers", id, "activity"] as const,
  territoryOverview: ["territory", "overview"] as const,
  regions: ["territory", "regions"] as const,
  municipalities: ["territory", "municipalities"] as const,
  municipality: (id: string) => ["territory", "municipalities", id] as const,
  geo: ["territory", "geo"] as const,
  events: ["events"] as const,
  event: (id: string) => ["events", id] as const,
  eventBySlug: (slug: string) => ["events", "slug", slug] as const,
  eventDashboard: (id: string) => ["events", id, "dashboard"] as const,
  eventRegistrations: (id: string) => ["events", id, "registrations"] as const,
  registrations: ["registrations"] as const,
  checkinEvents: ["checkin", "events"] as const,
  checkinSession: (eventId: string) => ["checkin", eventId] as const,
  certificates: ["certificates"] as const,
  evaluations: (eventId?: string) => ["evaluations", eventId ?? "all"] as const,
  evaluationSummary: (eventId?: string) => ["evaluations", eventId ?? "all", "summary"] as const,
  campaigns: ["campaigns"] as const,
  campaign: (id: string) => ["campaigns", id] as const,
  journeys: ["journeys"] as const,
  journey: (id: string) => ["journeys", id] as const,
  segments: ["segments"] as const,
  segmentEstimate: (key: string) => ["segments", "estimate", key] as const,
  dashboard: (period: string) => ["dashboard", period] as const,
  priorities: ["dashboard", "priorities"] as const,
  recentActivity: (limit: number) => ["activity", limit] as const,
  monthly: ["dashboard", "monthly"] as const,
  upcoming: ["dashboard", "upcoming"] as const,
  health: ["dashboard", "health"] as const,
  radarSignals: ["radar", "signals"] as const,
  radarOpportunities: ["radar", "opportunities"] as const,
  radarRecommendations: ["radar", "recommendations"] as const,
  radarRegions: ["radar", "regions"] as const,
  goals: ["goals"] as const,
  reports: ["reports"] as const,
  search: (q: string) => ["search", q] as const,
  notifications: ["notifications"] as const,
  users: ["users"] as const,
  integrations: ["integrations"] as const,
  audit: ["audit"] as const,
  tasks: ["tasks"] as const,
  participantHome: ["portal", "participant"] as const,
  chamberHome: (id: string) => ["portal", "chamber", id] as const,
}
